version: 2

registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.GH_PACKAGES_NPM_READ_TOKEN}}

updates:
  - package-ecosystem: "npm"
    registries:
      - npm-github
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "main"
    labels:
      - "dependencies"
