name: Canary Release

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publishing 🚀
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      # - run: npm set '//npm.pkg.github.com/:_authToken=${{ secrets.RELEASE_PACKAGE_TOKEN }}'
      - run: npm set @boonya:registry=https://npm.pkg.github.com/
      - run: npm ci
      - run: npm run build
      - run: |
          lerna publish --canary --yes \
            --preid canary \
            --pre-dist-tag canary
        env:
          NODE_AUTH_TOKEN: ${{ secrets.RELEASE_PACKAGE_TOKEN }}
