name: Release 🚀

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  ghcr:
    uses: ./.github/workflows/release-ghcr.yml
    secrets: inherit

  npm:
    uses: ./.github/workflows/release-npm.yml
    secrets: inherit
